<?php
require '../../vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;

// 1) Lista EXACTA de tus cabeceras, en orden
$headers = [
    'Bodega',
    'Referencia',
    'Línea Referencia',
    'Maneja Descripción A',
    'Cantidad Mínima a Pr',
    'Clase1',
    'Clase2',
    'Producto Frio',
    'Descripción',
    'Unidad',
    'Estado Articulo',
    'Último Precio Compra',
    'Precio Venta',
    'Dcto Venta',
    'Tipo Iva',
    'Tipo Retención',
    'Punto Mínimo',
    'Punto Máximo',
    'Costo Prom Inicial A',
    'Costo Prom Inicial M',
    'Costo Promedio Actua',
    'Saldo Inicial Año',
    'Saldo Inicial Mes',
    'Entradas Mes',
    'Salidas Mes',
    'Fecha Última Entrada',
    'Fecha Última Salida',
    'Manejo Estadísticas',
    'Imp Hortifoticula',
    'Tiempo Reposición',
    'Ubicación',
    'Valor Ajuste Actual',       // **repetida**
    'Factor Venta',
    'Peso Unidad Compra',
    'Peso Unidad Venta',
    'Unidad Compra',
    'Rentabilidad',
    'Comisión Ref',
    'Valor Ajuste Ini Mes',      // **repetida**
    'Valor Ajuste Ini Año',
    'Id Cuenta Ajuste',
    'Id Cuenta Correcc Mo',
    'Referencia Ajustada_',
    'Código Barras',
    'Valor Ajuste Actual',       // **repetida**
    'Valor Ajuste Ini Mes',      // **repetida**
    'Id Referencia',
    'Unidad de Empaque',
    'Control Existencia',
    'Id Cargos',
    'Clase3',
    'Maneja Accesorio',
    'Bodega Accesorio',
    'Referencia Accesorio',
    'Impulsar',
    'Precio Venta Sugerid',
    'Bodega Sustituto',
    'Referencia Sustituto',
    'Tipo Iva Devolución',
    'Tipo de Referencia',
    'Venta al Público',
    'Id Analisis',
    'Tipo Iva Compras',
    'Tipo Iva Dev Compras',
    'Código Arancelario',
    'Cuenta Costo Ajustad',      // **repetida**
    'Cuenta Contable',
    'Cuenta Compras',
    'Cuenta Costo',
    'Cuenta Inventario',
    'Cuenta Ajuste',
    'Cuenta Corecc Monet',
    'Cuenta Dev Ventas',
    'Cuenta Dev Compras',
    'Maneja Lote',
    'Maneja Serial',
    'Cuenta Ipoconsumo',
    'Cuenta Estampillas',
    'Maneja CUM',
    'Tipo Impuesto al Con',
    'Para Produccion',
    'Costo Estandar',
    'Cuenta MP',
    'Cuenta MOD',
    'Cuenta CIF',
    'Cuenta ST',
    'Cuenta PP',
    'Tipo CREE',
    'Cuenta Ventas NIIF',
    'Cuenta Devolucion Ve',
    'Cuenta Compras NIIF',
    'Cuenta Devolución Co',
    'Cuenta Costo NIIF',
    'Cuenta Inventario NI',
    'Cuenta Ajuste NIIF',
    'Cuenta Corrección NI',
    'Cuenta Costo Ajustad',      // **repetida**
    'Cuenta IpoConsumo NI',
    'Cuenta Estampillas NI',
    'Cuenta MP NIIF',
    'Cuenta MOD NIIF',
    'Cuenta CIF NIIF',
    'Cuenta STN NIIF',
    'Cuenta PP NIIF',
    'Aplica VNR para NIIF',
    'Valor Gasto Venta NI',
    'Cuenta Valor Gasto V',
    'Precio Minimo',
    'Precio Maximo',
    'Factor Conversion',
    'Costo Promedio Inici',
    'Costo Promedio Actua',
    'Ultimo Precio Compra',
    'Proteger Precio de V',
    'Existencia Actual Re',
];

// 2) Valores de tu fila de ejemplo (reemplaza por tu propia lista de literales)
$values = [
    1,
    'AB301222BY',
    'AB',
    'N',
    0,
    "",
    "",
    "N",
    "SALSAS",
    "KILOS",
    "",
    0,
    0,
    0,
    99,
    99,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    "10/01/2023",
    "10/01/2023",
    "S",
    "S",
    0,
    "",
    0,
    0,
    1,
    1,
    "KILOS",
    0,
    0,
    0,
    0,
    "",
    "",
    "N",
    "",
    0,
    0,
    "N",
    0,
    "N",
    "",
    "",
    "N",
    "",
    "",
    "N",
    0,
    "",
    "",
    99,
    "N",
    "",
    "N",
    99,
    99,
    "",
    "",
    "",
    "",
    "73709501",
    "18059502",
    "",
    "",
    "",
    "",
    "S",
    "N",
    "",
    "",
    "N",
    99,
    "N",
    0,
    "",
    "",
    "",
    "",
    "",
    99,
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "N",
    0,
    "",
    0,
    0,
    "N",
    0,
    0,
    0,
    "N",
    0
];

// 3) Generamos el código completo y lo volcamos a mapping.php
$output = "<?php\n\$sheet = \$spreadsheet->getActiveSheet();\n\n";

// Bloque de cabeceras
foreach ($headers as $i => $title) {
    $col = Coordinate::stringFromColumnIndex($i + 1);
    $output .= "\$sheet->setCellValue('{$col}1', '{$title}');\n";
}

$output .= "\n";  // separador

// Bloque de valores
foreach ($values as $i => $val) {
    $col = Coordinate::stringFromColumnIndex($i + 1);
    // Marca si el header correspondiente está repetido
    $repeat = substr_count(implode("\n", $headers), $headers[$i]) > 1
            ? " // **repetida**"
            : "";
    // Si es string, encierra en comillas
    $lit = is_string($val) ? "'{$val}'" : $val;
    $output .= "\$sheet->setCellValue(\"{$col}{\$fila}\", {$lit} ?? 'N/A');{$repeat}\n";
}

file_put_contents(__DIR__ . '/mapping.php', $output);

echo "✅ He generado el archivo mapping.php con tus setCellValue sin usar while ni echo en producción.\n";
